### ISSUE TITLE
arm support?

### ISSUE THREAD

**Issue by havu0** [mlaurenzano/PEBIL#5]
is there any plan support ARM binary?

**Comment by mlaurenzano** [comment]
No, there will not be ARM support in PEBIL. However, there is support planned among three other projects that I am aware of for ARM binary instrumentation.
EPAX - https://github.com/epanalytics/EPAX
DyninstAPI - http://www.dyninst.org/dyninst
Valgrind - http://valgrind.org/info/platforms.html
