### ISSUE TITLE
pebil failed during make it

### ISSUE THREAD

**Issue by 1Husin-Alhaj** [mlaurenzano/PEBIL#6]
I configured it like this:
sudo ./configure --enable-mpi=no --enable-static=yes
then I typed:
sudo make clean all install
please, why I always get this error :( 

g++ -static -g -O2 -std=gnu++0x -DHAVE_UNORDERED_MAP  -DPEBIL_VER="\"2.1.0\"" -w -o pebil.static S_pebil.o -I. -I../include -I../external/udis86-1.7/ -I../instcode ../src/libpebilinst.a -L../external/udis86-1.7/libudis86/.libs -ludis86 libBasicBlockCounterTool.a libCacheSimulationTool.a libCallReplaceTool.a libClassificationTool.a libFunctionCounterTool.a libFunctionTimerTool.a libMinimalTool.a libLoopInterceptTool.a libTauFunctionTraceTool.a libDeadRegisterSquasherTool.a ../src/libpebilinst.a -L../external/udis86-1.7/libudis86/.libs -ludis86
rm S_DeadRegisterSquasher.o S_CallReplace.o S_FunctionTimer.o S_CacheSimulation.o S_Classification.o S_LoopIntercept.o S_Minimal.o S_FunctionCounter.o S_TauFunctionTrace.o S_BasicBlockCounter.o
make[1]: Leaving directory '/home/ddems/Documents/PEBIL-master/tools'
scripts/blacklist.sh > scripts/inputlist/autogen-system.func
scripts/blacklist.sh: line 46: -o: command not found
Makefile:63: recipe for target 'scripts/inputlist/autogen-system.func' failed
make: *** [scripts/inputlist/autogen-system.func] Error 127
ddems@ddems-G41MT-S2:~/Documents/PEBIL-master$

**Comment by mlaurenzano** [comment]
Seems like configure isn't finding a fortran compiler. In `testapps/Makefile`, is your 3rd line empty? If so, you may need to explicitly specify the fortran compiler (e.g., something like `FC=gfortran ./configure <other_stuff>`)
