### ISSUE TITLE
PEBIL project progress 

### ISSUE THREAD

**Issue by vysocky** [mlaurenzano/PEBIL#7]
Dear developers, I don't see any commits since 2017. Is the PEBIL project closed?

**Comment by mlaurenzano** [comment]
@vysocky I'm not actively maintaining this repo anymore, though there's a group maintaining a private version that you may be able to route questions and comments to. I can connect you to them if you're interested. Feel free to reach out to me at michael.laurenzano@gmail.com for the connect.
