### ISSUE TITLE
Segmentation fault (core dumped) occurred.

### ISSUE THREAD

**Issue by xinnaz** [mlaurenzano/PEBIL#8]
I have built pebil successfully in the bin directory and $ pebil --help can work well. But when l ran the examples in INSTALL, segmentation fault (core dumped) occurred. For example, when l use:  $ pebil --lib lib --typ ide src/pebil
The result is:
[pebil-instr] Converting --typ ide to --tool INVALID
Segmentation fault (core dumped)

**Comment by accauble** [comment]
Hi @Nana-nn. You can find a more up-to-date version of PEBIL [here](https://github.com/epanalytics/PEBIL).
